---

- hosts: localhost
  connection: local

  tasks:
    - name: install personal cli applications
      homebrew: name={{item}} state=latest
      with_items:
        - mupen64plus
    - name: install personal applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - disk-inventory-x
        - google-hangouts
        - keepassx
        - master-password
        - mamp
        - owncloud
        - shuttle
        - sixtyforce
        - skype
        - spectacle
        - steam
        - vox
        - vox-preferences-pane
        - youtube-to-mp3

  roles:
    - profile-developer
  vars:
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: false
