---

- hosts: localhost
  connection: local

  tasks:
    - name: install brew applications
      homebrew: name={{item}} state=latest
      with_items:
        #- node
        #- docker
        #- docker-compose
        #- docker-machine
        #- docker-machine-driver-xhyve
        #- apm-bash-completion
        #- dinghy
        #- drush
        - git
        #- git-extras
        #- mupen64plus
    #- shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    #  become: yes
    #- shell: chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    #  become: yes
    - name: install homebrew cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        # Personal apps
        #- disk-inventory-x
        - google-hangouts
        #- owncloud
        #- keepassx
        #- shuttle
        #- sixtyforce
        #- skype
        #- spectacle
        #- steam
        #- vox
        #- vox-preferences-pane
        #- youtube-to-mp3

  roles:
    - profile-developer
  vars:
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: false
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
      #- domain: 'NSGlobalDomain'
      #  key: 'NSTableViewDefaultSizeMode'
      #  type: integer
      #  value: 1
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      #- domain: 'NSGlobalDomain'
      #  key: 'KeyRepeat'
      #  type: integer
      #  value: 2
      #- domain: 'NSGlobalDomain'
      #  key: 'InitialKeyRepeat'
      #  type: integer
      #  value: 15
      #- domain: 'com.apple.menuextra.clock'
      #  key: 'DateFormat'
      #  type: string
      #  value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      #- domain: 'com.apple.finder'
      #  key: 'FXPreferredViewStyle'
      #  type: string
      #  value: "clmv"
      #- domain: 'NSGlobalDomain'
      #  key: 'NSNavPanelExpandedStateForSaveMode'
      #  type: boolean
      #  value: true
      #- domain: 'NSGlobalDomain'
      #  key: 'PMPrintingExpandedStateForPrint'
      #  type: boolean
      #  value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      #- domain: 'com.apple.dock'
      #  key: 'autohide-time-modifier'
      #  type: int
      #  value: 0
      #- domain: 'com.apple.dock'
      #  key: 'autohide-delay'
      #  type: int
      #  value: 0
      #- domain: 'NSGlobalDomain'
      #  key: 'NSQuitAlwaysKeepsWindows'
      #  type: boolean
      #  value: false
      #- domain: 'com.apple.desktopservices'
      #  key: 'DSDontWriteNetworkStores'
      #  type: boolean
      #  value: true
      #- domain: 'com.apple.print.PrintingPrefs'
      #  key: 'Quit When Finished'
      #  type: boolean
      #  value: true
      #- domain: 'com.apple.Safari'
      #  key: 'IncludeInternalDebugMenu'
      #  type: boolean
      #  value: true
      #- domain: 'com.apple.Safari'
      #  key: 'IncludeDevelopMenu'
      #  type: boolean
      #  value: true
      #- domain: 'com.apple.Safari'
      #  key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
      #  type: boolean
      #  value: true
      #- domain: 'com.apple.Safari'
      #  key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
      #  type: boolean
      #  value: true
      #- domain: 'NSGlobalDomain'
      #  key: 'WebKitDeveloperExtras'
      #  type: boolean
      #  value: true
