---

- hosts: localhost
  connection: local

  tasks:
    - name: install brew applications
      homebrew: name={{item}} state=latest
      with_items:
        #- node
        #- docker
        #- docker-compose
        #- docker-machine
        #- docker-machine-driver-xhyve
        #- apm-bash-completion
        #- dinghy
        #- drush
        - git
        #- git-extras
        #- mupen64plus
    #- shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    #  become: yes
    #- shell: chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    #  become: yes
    - name: install homebrew cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        # Personal apps
        #- disk-inventory-x
        - google-hangouts
        #- owncloud
        #- keepassx
        #- shuttle
        #- sixtyforce
        #- skype
        #- spectacle
        #- steam
        #- vox
        #- vox-preferences-pane
        #- youtube-to-mp3

  roles:
    - profile-developer
