---

- name: install applications for all users
  homebrew_cask: name={{item}} state=present install_options=force
  with_items:
    - alfred
    - box-sync
    - flux
    - microsoft-lync
    - unrarx
    - vlc
    - yed

- name: install quick look plugins for all users
  homebrew_cask: name={{item}} state=present install_options=force
  with_items:
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - qlprettypatch
    - quicklook-csv
    - betterzipql
    - qlimagesize
    - webpquicklook
    - suspicious-package
