---
osx_defaults:
  - domain: 'com.apple.dock'
    key: 'orientation'
    type: string
    value: bottom
  - domain: 'com.apple.dock'
    key: 'autohide'
    type: boolean
    value: true
  - domain: 'NSGlobalDomain' # Set sidebar icon size to medium
    key: 'NSTableViewDefaultSizeMode'
    type: integer
    value: 2
  - domain: 'com.apple.screencapture'
    key: 'type'
    type: string
    value: png
  #- domain: 'NSGlobalDomain'
  #  key: 'KeyRepeat'
  #  type: integer
  #  value: 2
  #- domain: 'NSGlobalDomain'
  #  key: 'InitialKeyRepeat'
  #  type: integer
  #  value: 15
  - domain: 'com.apple.menuextra.clock'
    key: 'DateFormat'
    type: string
    value: EEE MMM d  HH:mm
  - domain: 'com.apple.menuextra.battery'
    key: 'ShowPercent'
    type: string
    value: 'YES'
  #- domain: 'com.apple.finder'
  #  key: 'FXPreferredViewStyle'
  #  type: string
  #  value: "clmv"
  #- domain: 'NSGlobalDomain'
  #  key: 'NSNavPanelExpandedStateForSaveMode'
  #  type: boolean
  #  value: true
  - domain: 'NSGlobalDomain' # Expand print panel by default
    key: 'PMPrintingExpandedStateForPrint'
    type: boolean
    value: true
  - domain: 'NSGlobalDomain' # Expand print panel by default
    key: 'PMPrintingExpandedStateForPrint2'
    type: boolean
    value: true
  - domain: 'com.apple.dock'
    key: 'tilesize'
    type: float
    value: 32
  - domain: 'com.apple.dock'
    key: 'autohide-time-modifier'
    type: int
    value: 0
  - domain: 'com.apple.dock'
    key: 'autohide-delay'
    type: int
    value: 0
  #- domain: 'NSGlobalDomain'
  #  key: 'NSQuitAlwaysKeepsWindows'
  #  type: boolean
  #  value: false
  #- domain: 'com.apple.desktopservices'
  #  key: 'DSDontWriteNetworkStores'
  #  type: boolean
  #  value: true
  - domain: 'com.apple.print.PrintingPrefs' # Automatically quit printer app once the print jobs complete
    key: 'Quit When Finished'
    type: boolean
    value: true
  - domain: 'com.apple.Safari'
    key: 'IncludeInternalDebugMenu'
    type: boolean
    value: true
  - domain: 'com.apple.Safari'
    key: 'IncludeDevelopMenu'
    type: boolean
    value: true
  - domain: 'com.apple.Safari'
    key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
    type: boolean
    value: true
  - domain: 'com.apple.Safari'
    key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
    type: boolean
    value: true
  - domain: 'NSGlobalDomain'
    key: 'WebKitDeveloperExtras'
    type: boolean
    value: true

# Increase window resize speed for Cocoa applications
#defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Expand save panel by default
#defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
#defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Save to disk (not to iCloud) by default
#defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Disable the “Are you sure you want to open this application?” dialog
#defaults write com.apple.LaunchServices LSQuarantine -bool false

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
#/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Disable smart dashes as they’re annoying when typing code
#defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
