---

- name: install taps
  homebrew_tap: tap={{item}} state=present
  with_items:
    - caskroom/versions
    - codekitchen/dinghy

- name: install cli applications for developers
  homebrew: name={{item}} state=latest
  with_items:
    - coreutils
    - findutils
    - git
    - git-extras
    - htop   
    - moreutils
    - nvm
    - rsync
    - sqlmap
    - wget
    #- docker
    #- docker-compose
    #- docker-machine
    #- docker-machine-driver-xhyve
    #- apm-bash-completion
    #- dinghy
    #- drush
#- shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
#  become: yes
#- shell: chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
#  become: yes
- name: install applications for developers
  homebrew_cask: name={{item}} state=present
  with_items:
    - dash
    - docker
    - kitematic
    - imagealpha
    - imageoptim
    - macdown
    - phpstorm
    - postman
    - sequel-pro
    - sourcetree
    - sqlitebrowser
    - sublime-text
    - wireshark

- name: create ~/projects directory
  file: path=~/projects state=directory
