---

- name: install taps
  homebrew_tap: tap={{item}} state=present
  with_items:
    - caskroom/versions
    - codekitchen/dinghy

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - coreutils
    - findutils
    - htop
    - moreutils
    - nvm
    - rsync
    - sqlmap
    - wget

- name: install developer homebrew cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - dash
    - docker
    - kitematic
    - imagealpha
    - imageoptim
    - macdown
    - mamp
    - phpstorm
    - postman
    - sequel-pro
    - sourcetree
    - sqlitebrowser
    - sublime-text
    - wireshark

